battery:
  mass: 0.02295
  scale: 0.5
driver:
  mass: 0.0006
  scale: 0.5
hand_weight:
  mass: 0.00248
  scale: 0.5
hip_motor:
  mass: 0.00141
  scale: 0.5
l_arm:
  mass: 0.00058
  scale: 0.5
l_leg:
  mass: 0.0033
  scale: 0.5
mcu:
  mass: 0.00402
  scale: 0.5
r_arm:
  mass: 0.00047
  scale: 0.5
r_leg:
  mass: 0.00317
  scale: 0.5
weight:
  mass: 0.021
  scale: 0.5
