battery:
  mass: 0.02
  scale: 1
driver:
  mass: 0.0006
  scale: 1
hand_weight:
  mass: 0.00248
  scale: 1
hip_motor:
  mass: 0.00141
  scale: 1
l_arm:
  mass: 0.00058
  scale: 1
l_leg:
  mass: 0.0033
  scale: 1
mcu:
  mass: 0.00402
  scale: 1
r_arm:
  mass: 0.00047
  scale: 1
r_leg:
  mass: 0.00317
  scale: 1
weight:
  mass: 0.022
  scale: 1
